openapi: 3.0.0
info:
  title: pick.me API
  description: |
    This API belongs to the pick.me application. Pick.me is a Web-Application
    which allows a user to manage private packing lists for several different bags.
  version: 1.0.0

paths:
  /users:
      get:
        summary: Returns a list of all registred users.
        description: |
          This resource returns a list of all registered users.
        responses:
          '200':
            description: A JSON array of bag templates.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: Unique ID of the user.
                      username:
                        type: string
                        description: The user name.
                      mail:
                        type: string
                        description: The mail adress.
                      password:
                        type: string
                        description: The password.
      post:
        summary: Create/update a user.
        description: |
          If the user is nonexistent, the user is created. If the user has a known
          id, the existing user is updated.
        requestBody:
          description: The user.
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: |
                      (optional) The unique ID of the user. (This property is only
                      required, if you want to update an existing user.)
                  username:
                    type: string
                    description: The user name.
                  mail:
                    type: string
                    description: The mail adress.
                  password:
                    type: string
                    description: The password.
        responses:
          '200':
            description: |
              The user was successfully created/updated. The response contains
              the recently created/updated user. (If a new user was created, the
              response contains the id which was assigned to the user.)
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique ID of the user.
                    username:
                      type: string
                      description: The user name.
                    mail:
                      type: string
                      description: The mail adress.
                    password:
                      type: string
                      description: The password.
  /bag_templates:
    get:
      summary: Returns a list of all bag templates.
      description: |
        This resource returns a list of all available bag templates. These bag
        templates are preconfigured bags with an characterizing illustration
        and a name suggestion.
      responses:
        '200':
          description: A JSON array of bag templates.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique ID of the bag template.
                    name:
                      type: string
                      description: A name suggestion for the bag.
                    illustration:
                      type: string
                      description: The location of an illustration characterizing the bag.
  /my_bags:
    get:
      summary: Returns a list of all your bags.
      description: |
        This resource returns a list of all your bags. Each of your bags is
        characterized with the preconfigured illustration and the name you've
        assigned. Additionally each of your bags contains the items you've
        added.
      responses:
        '200':
          description: A JSON array of bags.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique ID of the bag.
                    name:
                      type: string
                      description: The name of the bag.
                    illustration:
                      type: string
                      description: The location of an illustration characterizing the bag.
                    dueDate:
                      type: string
                      format: date-time
                      description: (optional) Time at which the bag must be ready packed. (ISO 8601 format)
                    content:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the item.
                          state:
                            type: boolean
                            description: Describes whether the item is packed or not.
    post:
      summary: Create/update a bag.
      description: |
        If the bag is nonexistent, the bag is created. If the bag has a known
        id, the existing bag is updated.
      requestBody:
        description: The bag.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                  description: |
                    (optional) The unique ID of the bag. (This property is only
                    required, if you want to update an existing bag.)
                name:
                  type: string
                  description: The name of the bag.
                illustration:
                  type: string
                  description: The location of an illustration characterizing the bag.
                dueDate:
                  type: string
                  format: date-time
                  description: (optional) Time at which the bag must be ready packed. (ISO 8601 format)
                content:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the item.
                      state:
                        type: boolean
                        description: Describes whether the item is packed or not.
      responses:
        '200':
          description: |
            The bag was successfully created/updated. The response contains
            the recently created/updated bag. (If a new bag was created, the
            response contains the id which was assigned to the bag.)
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Unique ID of the bag.
                  name:
                    type: string
                    description: The name of the bag.
                  illustration:
                    type: string
                    description: The location of an illustration characterizing the bag.
                  dueDate:
                    type: string
                    format: date-time
                    description: (optional) Time at which the bag must be ready packed. (ISO 8601 format)
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the item.
                        state:
                          type: boolean
                          description: Describes whether the item is packed or not.
  /my_bags/{id}:
    delete:
      summary: Deletes a bag.
      description: |
        Deletes the bag with the given id.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the bag to be deleted
      responses:
        '200':
          description: |
            If the bag has successfully been deleted.
  /my_bags/{id}/share_on_whatsapp:
    get:
      summary: |
        Share a bag on whatsapp.
      description: |
        This resource delivers a custom whatsapp uri. Opened in a broser the
        uri starts whatsapp. After that it inserts an text representation of
        the bag in a new message. This allows the user to share a bag on
        whatsapp.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the bag to be shared.
      responses:
        '200':
          description: |
            The uri has been created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  uri:
                    type: string
                    description: Whatsapp custom uri.

