openapi: 3.0.0
info:
  title: pick.me API
  description: |
    This API belongs to the pick.me application. Pick.me is a Web-Application
    which allows a user to manage private packing lists for several different bags.
  version: 1.0.0

paths:
  /bag_templates:
    get:
      summary: Returns a list of all bag templates.
      description: |
        This resource returns a list of all available bag templates. These bag
        templates are preconfigured bags with an characterizing illustration
        and a name suggestion.
      responses:
        '200':
          description: A JSON array of bag templates.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique ID of the bag template.
                    name:
                      type: string
                      description: A name suggestion for the bag.
                    illustration:
                      type: string
                      description: The location of an illustration characterizing the bag.
  /my_bags:
    get:
      summary: Returns a list of all your bags.
      description: |
        This resource returns a list of all your bags. Each of your bags is
        characterized with the preconfigured illustration and the name you've
        assigned. Additionally each of your bags contains the items you've
        added.
      responses:
        '200':
          description: A JSON array of bags.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique ID of the bag.
                    name:
                      type: string
                      description: The name of the bag.
                    illustration:
                      type: string
                      description: The location of an illustration characterizing the bag.
                    content:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the item.
                          state:
                            type: boolean
                            description: Describes whether the item is packed or not.
