openapi: 3.0.0
info:
  title: pick.me API
  description: |
    This API belongs to the pick.me application. Pick.me is a Web-Application
    which allows a user to manage private packing lists for several different bags.
  version: 1.0.0

paths:
  /bags:
    get:
      summary: Returns a list of all bags.
      description: |
        This resource returns a list of all available bags. These bags are
        preconfigured with an illustration and a name suggestion.
      responses:
        '200':
          description: A JSON array of bags.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: A name suggestion for the bag.
                    illustration:
                      type: string
                      description: The location of an illustration characterizing the bag.
